In [ ]:
import numpy as np
AttScores=np.array([0.1,0.5,0.3, 0.1]) 
Input= np.array([[1,0,2],[0,1,3],[1,3,0],[0,0,0]])
print(AttScores)
print(Input)
print(AttScores@Input)

[0.1 0.5 0.3 0.1]
[[1 0 2]
 [0 1 3]
 [1 3 0]
 [0 0 0]]
[0.4 1.4 1.7]


In [ ]:
from scipy.special import softmax
Query=np.array([0,0,1])
UnnormScores=Input@Query
AttScores=softmax(UnnormScores)
print(AttScores)
print(Input)
print(AttScores@Input)

[0.25069239 0.68145256 0.03392753 0.03392753]
[[1 0 2]
 [0 1 3]
 [1 3 0]
 [0 0 0]]
[0.28461991 0.78323514 2.54574246]


In [ ]:
[[0.6685863697825855, 0.9865099796400376], 
 [0.32297881307708, 0.9908870158650515], 
 [0.8359169063921157, 0.5443776713017927], 
 [0.5363888029267118, 0.34755850459471804], 
 [0.5966372342560426, 0.9834742307894673], 
 [0.7371274295314912, 0.03279590013405109], 
 [0.08580648148402137, 0.2850655085982621], 
 [0.584942134340805, 0.7981720699451806], 
 [0.19604496972304086, 0.991819073359733], 
 [0.5622511488322055, 0.07928952553499002], 
 [0.24152151330089744, 0.2865696384305756], 
 [0.882594506643994, 0.5949729821472712], 
 [0.10820233432771786, 0.8549971123651271], 
 [0.18754460128195194, 0.6303661925298489], 
 [0.3551051497971416, 0.9452980688158904], 
 [0.6525044770663634, 0.8054232618991838]]
 
[[[0.8638059436915633, 0.4002290439648929, 0.8174398057982054, 0.34082478315585973, 0.5565832130592809], 
  [0.08497737591188492, 0.7853885140384725, 0.1645895575029136, 0.6294907704137637, 0.8169862258229014]], 
 [[0.21527072709338957, 0.9185427760457524, 0.5167378860756242, 0.12177789993763499, 0.4201289643444214], 
  [0.8389450071463863, 0.6238637143288427, 0.5098771768082815, 0.1436853463091461, 0.12036561608743845]], 
 [[0.8347050184618267, 0.12339875692133984, 0.13629086964943626, 0.623950910768403, 0.7092189295761365], 
  [0.9578703072530402, 0.31612669923975534, 0.44018179806384916, 0.26615330385390035, 0.2745979551030847]]]
[0.6574440445518804, 0.3253787051567585, 0.3119672663686287]